//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantillas_Tareas
    {
        public int id { get; set; }
        public int plantilla_id { get; set; }
        public int tarea_id { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
