//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuestos_Tareas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presupuestos_Tareas()
        {
            this.PresupuestosTareas_Recursos = new HashSet<PresupuestosTareas_Recursos>();
        }
    
        public int id { get; set; }
        public int presupuesto_id { get; set; }
        public int tarea_id { get; set; }
    
        public virtual Presupuesto Presupuesto { get; set; }
        public virtual Tarea Tarea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestosTareas_Recursos> PresupuestosTareas_Recursos { get; set; }
    }
}
