//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recurso()
        {
            this.PresupuestosTareas_Recursos = new HashSet<PresupuestosTareas_Recursos>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public int valorHora { get; set; }
        public int rango_id { get; set; }
        public int rol_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestosTareas_Recursos> PresupuestosTareas_Recursos { get; set; }
        public virtual Rango Rango { get; set; }
        public virtual Role Role { get; set; }
    }
}
